---
title: "Activity Visualization"
subtitle: "An introductive project to R + an analysis of how I have spent my time over time"
author: "Maya Luna"
date: "4.28.2025"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This project will be making use of the tidyverse and lubridate packages.

```{r, include=FALSE}
library(tidyverse)
library(lubridate)
library(dplyr)
df <- read.csv("rawdata/ActivityTracker64.csv")
future <- read.csv("G:/My Drive/activitytracker/stt_records_automatic.csv")
```

Legend:
```{r}
category_colors <- c(
    "Work" = "#673ab7",
    "Brain Blasters" = "#3f51b5",
    "Leisure" = "#2196f3",
    "Life Duties" = "#f53639",
    "Human Upkeep" = "#ffeb3b",
    "Socializing" = "#4caf50",
    "transportation" = "#ffc107",
    "Vices" = "#8bc34a",
    "Mindfulness" = "#ef4091"
)
```

```{r, include=FALSE}
df <- df %>%
  mutate(
    time_started = ymd_hms(time_started),
    time_ended = ymd_hms(time_ended),
    date = as.Date(time_started)
  )

monthly <- df %>%
    mutate(
        month = format(date, "%m"),
        year = format(date, "%Y")
        ) %>%
        group_by(month, year, categories) %>%
        summarise(
            total_hours = (duration_minutes/60) %>% sum(na.rm = TRUE),
            .groups='drop'
        ) %>%
        mutate(
    month_year = as.Date(paste(year, month, "01", sep = "-"))
  )
```


```{r}
one <- ggplot(monthly, aes(x = month_year, y = total_hours, color = categories, group = categories)) +
    geom_line(linewidth = 2) +
    scale_color_manual(values = category_colors) +
    labs(
        x = "Date",
        y = "Total Hours") +
        scale_x_date(date_labels = "%b %Y", date_breaks = "1 month") + 
        theme_minimal() +
        theme(
            panel.background = element_rect(fill = "black"),
            axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
            panel.grid.minor = element_blank()
            )
```

## Time spent per category over time
```{r echo=FALSE, fig.align = "center", fig.width = 15, fig.height = 10}
one
```

plot = the area behind the chart

panel = the chart itself


```{r}
activity.change <- function(category) {
    monthly %>%
        filter(categories == category) %>%
        arrange(month_year) %>%
        mutate(
            change = total_hours - lag(total_hours),
            percent_change = (change/lag(total_hours)) * 100
        ) %>%
        select(month_year, total_hours, change, percent_change)
}

work.change <- activity.change("Work")
leisure.change <- activity.change("Leisure")
socializing.change <- activity.change("Socializing")
vices.change <- activity.change("Vices")
humanupkeep.change <- activity.change("Human Upkeep")
transportation.change <- activity.change("transportation")
lifeduties.change <- activity.change("Life Duties")
lifeduties.change <- activity.change("Brain Blasters")
mindfulness.change <- activity.change("Mindfulness")

mindfulness.change
work.change
leisure.change
```


```{r include=FALSE}
activity.change.all <- function() {
    monthly %>%
        arrange (categories, month_year) %>%
        group_by(categories) %>%
        mutate(
            change = total_hours - lag(total_hours),
            percent_change = (change / lag(total_hours)) * 100
        ) %>%
        ungroup() %>%
        select(categories, month_year, total_hours, change, percent_change)
}

activity.change.all()
```